### ISSUE TITLE
Support T1 <: T2 syntax 

### ISSUE THREAD

**Issue by MasonProtter** [thautwarm/CanonicalTraits.jl#17]
Currently, this creates a trait `InnerProd` which is a subtrait of `VecSpace`:
```julia
@trait VecSpace{F, V} >: InnerProd{F, V} where
  {F = V2F(V)} begin
  dot :: [V, V] => F
end
```
I feel this is kinda unclear, and awkward to read. Could we also support the reverse syntax? e.g.
```julia
@trait InnerProd{F, V} <: VecSpace{F, V} where 
  {F = V2F(V)} begin
  dot :: [V, V] => F
end
```
I find this much more legible and 'julian'.

**Comment by thautwarm** [comment]
This is fine. There are some trait implementations positioning premises later, such as that in Rust and PureScript.

**Comment by MasonProtter** [comment]
This package is really cool by the way! I think I knew about it a long time ago but didn't understand. Coming back now that I get type classes, this is great.
